# inventory.ini
[windows]
target_windows ansible_host=<WINDOWS_IP>

[windows:vars]
ansible_user=cyberrange
ansible_password=Cyberrange123!
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
ansible_winrm_scheme=https
ansible_ssh_common_args=-o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no