# inventory.ini
[windows]
target_windows ansible_host=<OPENSTACK_IP>

[windows:vars]
ansible_user=cyberrange
ansible_connection=winrm
ansible_winrm_transpor=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
ansible_winrm_schema=https
ansible_ssh_common_args=-o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no