# inventory.ini
[windows]
target_windows ansible_host=<OPENSTACK_IP>

[windows:vars]
# Credentials - pulled from ansible-vault
ansible_user=Administrator
# ansible_password="{{ vault_admin_password }}"

# WinRM over HTTPS instead of SSH
ansible_connection=winrm
ansible_winrm_transport=ssl
ansible_winrm_server_cert_validation=ignore
ansible_port=5986

# Route WinRM traffic through the CyberRange jump host
ansible_winrm_scheme=https
ansible_ssh_common_args=-o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no